site_name: Skeptic Framework
site_description: Documentation for the Skeptic Framework
site_author: KasCode
site_url: https://JKasCode.github.io/SkepticDocs/

repo_name: JKasCode/SkepticDocs
repo_url: https://github.com/JKasCode/SkepticDocs

copyright: "&copy; 2024 Skeptic Softworks, All Rights Reserved"

theme: 
  name: material
  logo: assets/skeptic.png
  favicon: assets/favicon.png
  
  palette:
    # Light 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    # Dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Light mode

  highlightjs: true
  hljs_languages:
    - lua

extra:
  social:
    - icon: fontawesome/solid/earth-americas
      link: https://skepticsoftworks.com
    - icon: fontawesome/brands/x-twitter 
      link: https://x.com/Aws_RBLX
    - icon: fontawesome/brands/tiktok
      link: https://www.tiktok.com/@aws_rblx
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@Aws_RBLX

extra_javascript:
  - javascripts/tags.js

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite