site_name: Skeptic Framework
site_description: Documentation for the Skeptic Framework
site_author: KasCode
site_url: https://JKasCode.github.io/SkepticDocs/

repo_name: JKasCode/SkepticDocs
repo_url: https://github.com/JKasCode/SkepticDocs

theme: 
  name: material
  
  palette:
    # Light 
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Dark mode
    # Dark
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: blue
      toggle:
        icon: material/weather-night
        name: Light mode

  highlightjs: true
  hljs_languages:
    - lua

extra_javascript:
  - javascripts/tags.js

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite